services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    platform: "linux/amd64"
    ports:
        -  "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5